/*
 * Copyright (c) 2015-2019, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
/** ============================================================================
 *  @file       CC1312R1_SMARTSENSOR.h
 *
 *  @brief      CC1312R1_SMARTSENSOR Board Specific header file.
 *
 *  The CC1312R1_SMARTSENSOR header file should be included in an application as
 *  follows:
 *  @code
 *  #include "CC1312R1_SMARTSENSOR.h"
 *  @endcode
 *
 *  ============================================================================
 */
#ifndef __CC1312R1_SMARTSENSOR_BOARD_H__
#define __CC1312R1_SMARTSENSOR_BOARD_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "contiki-conf.h"

/* Includes */
#include <ti/drivers/PIN.h>
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/ioc.h)

/* Externs */
extern const PIN_Config BoardGpioInitTable[];

/* Defines */
#define CC1312R1_SMARTSENSOR

/* Mapping of pins to board signals using general board aliases
 *      <board signal alias>                  <pin mapping>   <comments>
 */

/* Analog capable DIOs */
#define CC1312R1_SMARTSENSOR_DIO23_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO24_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO25_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO26_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO27_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO28_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO29_ANALOG          PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_DIO30_ANALOG          IOID_30

/* Digital IOs */
#define CC1312R1_SMARTSENSOR_STM_NRST              IOID_10
#define CC1312R1_SMARTSENSOR_STM_BOOT              IOID_11

/* Discrete Inputs */
#define CC1312R1_SMARTSENSOR_PIN_BTN1              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PIN_BTN2              PIN_UNASSIGNED

/* GPIO */
#define CC1312R1_SMARTSENSOR_GPIO_LED_ON           1
#define CC1312R1_SMARTSENSOR_GPIO_LED_OFF          0

/* I2C */
#define CC1312R1_SMARTSENSOR_I2C0_SCL0             PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_I2C0_SDA0             PIN_UNASSIGNED

/* I2S */
#define CC1312R1_SMARTSENSOR_I2S_ADO               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_I2S_ADI               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_I2S_BCLK              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_I2S_MCLK              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_I2S_WCLK              PIN_UNASSIGNED

/* LEDs */
#define CC1312R1_SMARTSENSOR_PIN_LED_ON            1
#define CC1312R1_SMARTSENSOR_PIN_LED_OFF           0
#define CC1312R1_SMARTSENSOR_PIN_RLED              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PIN_GLED              PIN_UNASSIGNED

/* PWM Outputs */
#define CC1312R1_SMARTSENSOR_PWMPIN0               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN1               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN2               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN3               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN4               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN5               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN6               PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_PWMPIN7               PIN_UNASSIGNED

/* SPI */
#define CC1312R1_SMARTSENSOR_SPI_FLASH_WP          IOID_3
#define CC1312R1_SMARTSENSOR_SPI_FLASH_HOLD        IOID_4
#define CC1312R1_SMARTSENSOR_SPI_FLASH_CS          IOID_6
#define CC1312R1_SMARTSENSOR_FLASH_CS_ON           0
#define CC1312R1_SMARTSENSOR_FLASH_CS_OFF          1

/* SPI Board */
#define CC1312R1_SMARTSENSOR_SPI0_MISO             IOID_2          /* RF1.20 */
#define CC1312R1_SMARTSENSOR_SPI0_MOSI             IOID_1          /* RF1.18 */
#define CC1312R1_SMARTSENSOR_SPI0_CLK              IOID_5           /* RF1.16 */
#define CC1312R1_SMARTSENSOR_SPI0_CSN              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_SPI1_MISO             PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_SPI1_MOSI             PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_SPI1_CLK              PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_SPI1_CSN              PIN_UNASSIGNED

/* UART Board */
#define CC1312R1_SMARTSENSOR_UART0_RX              IOID_8                 /* RXD Terminal */
#define CC1312R1_SMARTSENSOR_UART0_TX              IOID_9                 /* TXD Terminal */
#define CC1312R1_SMARTSENSOR_UART0_CTS             PIN_UNASSIGNED         /* CTS */
#define CC1312R1_SMARTSENSOR_UART0_RTS             PIN_UNASSIGNED         /* RTS */
#define CC1312R1_SMARTSENSOR_UART1_RX              IOID_12                /* IOID_12 RXD STM32 */
#define CC1312R1_SMARTSENSOR_UART1_TX              IOID_13                /* IOID_13 TXD STM32 */
#define CC1312R1_SMARTSENSOR_UART1_CTS             PIN_UNASSIGNED
#define CC1312R1_SMARTSENSOR_UART1_RTS             PIN_UNASSIGNED
/* For backward compatibility */
#define CC1312R1_SMARTSENSOR_UART_RX               CC1312R1_SMARTSENSOR_UART0_RX
#define CC1312R1_SMARTSENSOR_UART_TX               CC1312R1_SMARTSENSOR_UART0_TX
#define CC1312R1_SMARTSENSOR_UART_CTS              CC1312R1_SMARTSENSOR_UART0_CTS
#define CC1312R1_SMARTSENSOR_UART_RTS              CC1312R1_SMARTSENSOR_UART0_RTS

/*!
 *  @brief  Initialize the general board specific settings
 *
 *  This function initializes the general board specific settings.
 */
void CC1312R1_SMARTSENSOR_initGeneral(void);

/*!
 *  @brief  Turn off the external flash on LaunchPads
 *
 */
void CC1312R1_SMARTSENSOR_shutDownExtFlash(void);

/*!
 *  @brief  Wake up the external flash present on the board files
 *
 *  This function toggles the chip select for the amount of time needed
 *  to wake the chip up.
 */
void CC1312R1_SMARTSENSOR_wakeUpExtFlash(void);

/*!
 *  @def    CC1312R1_SMARTSENSOR_ADCBufName
 *  @brief  Enum of ADCBufs
 */
typedef enum CC1312R1_SMARTSENSOR_ADCBufName {
    CC1312R1_SMARTSENSOR_ADCBUF0 = 0,

    CC1312R1_SMARTSENSOR_ADCBUFCOUNT
} CC1312R1_SMARTSENSOR_ADCBufName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_ADCBuf0ChannelName
 *  @brief  Enum of ADCBuf channels
 */
typedef enum CC1312R1_SMARTSENSOR_ADCBuf0ChannelName {
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL0 = 0,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL1,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL2,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL3,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL4,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL5,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL6,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNEL7,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNELVDDS,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNELDCOUPL,
    CC1312R1_SMARTSENSOR_ADCBUF0CHANNELVSS,

    CC1312R1_SMARTSENSOR_ADCBUF0CHANNELCOUNT
} CC1312R1_SMARTSENSOR_ADCBuf0ChannelName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_ADCName
 *  @brief  Enum of ADCs
 */
typedef enum CC1312R1_SMARTSENSOR_ADCName {
    CC1312R1_SMARTSENSOR_ADC0 = 0,
    CC1312R1_SMARTSENSOR_ADC1,
    CC1312R1_SMARTSENSOR_ADC2,
    CC1312R1_SMARTSENSOR_ADC3,
    CC1312R1_SMARTSENSOR_ADC4,
    CC1312R1_SMARTSENSOR_ADC5,
    CC1312R1_SMARTSENSOR_ADC6,
    CC1312R1_SMARTSENSOR_ADC7,
    CC1312R1_SMARTSENSOR_ADCDCOUPL,
    CC1312R1_SMARTSENSOR_ADCVSS,
    CC1312R1_SMARTSENSOR_ADCVDDS,

    CC1312R1_SMARTSENSOR_ADCCOUNT
} CC1312R1_SMARTSENSOR_ADCName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_ECDHName
 *  @brief  Enum of ECDH names
 */
typedef enum CC1312R1_SMARTSENSOR_ECDHName {
    CC1312R1_SMARTSENSOR_ECDH0 = 0,

    CC1312R1_SMARTSENSOR_ECDHCOUNT
} CC1312R1_SMARTSENSOR_ECDHName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_ECDSAName
 *  @brief  Enum of ECDSA names
 */
typedef enum CC1312R1_SMARTSENSOR_ECDSAName {
    CC1312R1_SMARTSENSOR_ECDSA0 = 0,

    CC1312R1_SMARTSENSOR_ECDSACOUNT
} CC1312R1_SMARTSENSOR_ECDSAName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_ECJPAKEName
 *  @brief  Enum of ECJPAKE names
 */
typedef enum CC1312R1_SMARTSENSOR_ECJPAKEName {
    CC1312R1_SMARTSENSOR_ECJPAKE0 = 0,

    CC1312R1_SMARTSENSOR_ECJPAKECOUNT
} CC1312R1_SMARTSENSOR_ECJPAKEName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESCCMName
 *  @brief  Enum of AESCCM names
 */
typedef enum CC1312R1_SMARTSENSOR_AESCCMName {
    CC1312R1_SMARTSENSOR_AESCCM0 = 0,

    CC1312R1_SMARTSENSOR_AESCCMCOUNT
} CC1312R1_SMARTSENSOR_AESCCMName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESGCMName
 *  @brief  Enum of AESGCM names
 */
typedef enum CC1312R1_SMARTSENSOR_AESGCMName {
    CC1312R1_SMARTSENSOR_AESGCM0 = 0,

    CC1312R1_SMARTSENSOR_AESGCMCOUNT
} CC1312R1_SMARTSENSOR_AESGCMName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESCBCName
 *  @brief  Enum of AESCBC names
 */
typedef enum CC1312R1_SMARTSENSOR_AESCBCName {
    CC1312R1_SMARTSENSOR_AESCBC0 = 0,

    CC1312R1_SMARTSENSOR_AESCBCCOUNT
} CC1312R1_SMARTSENSOR_AESCBCName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESCTRName
 *  @brief  Enum of AESCTR names
 */
typedef enum CC1312R1_SMARTSENSOR_AESCTRName {
    CC1312R1_SMARTSENSOR_AESCTR0 = 0,

    CC1312R1_SMARTSENSOR_AESCTRCOUNT
} CC1312R1_SMARTSENSOR_AESCTRName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESECBName
 *  @brief  Enum of AESECB names
 */
typedef enum CC1312R1_SMARTSENSOR_AESECBName {
    CC1312R1_SMARTSENSOR_AESECB0 = 0,

    CC1312R1_SMARTSENSOR_AESECBCOUNT
} CC1312R1_SMARTSENSOR_AESECBName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_AESCTRDRBGName
 *  @brief  Enum of AESCTRDRBG names
 */
typedef enum CC1312R1_SMARTSENSOR_AESCTRDRBGName {
    CC1312R1_SMARTSENSOR_AESCTRDRBG0 = 0,

    CC1312R1_SMARTSENSOR_AESCTRDRBGCOUNT
} CC1312R1_SMARTSENSOR_AESCTRDRBGName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_SHA2Name
 *  @brief  Enum of SHA2 names
 */
typedef enum CC1312R1_SMARTSENSOR_SHA2Name {
    CC1312R1_SMARTSENSOR_SHA20 = 0,

    CC1312R1_SMARTSENSOR_SHA2COUNT
} CC1312R1_SMARTSENSOR_SHA2Name;

/*!
 *  @def    CC1312R1_SMARTSENSOR_TRNGName
 *  @brief  Enum of TRNG names
 */
typedef enum CC1312R1_SMARTSENSOR_TRNGName {
    CC1312R1_SMARTSENSOR_TRNG0 = 0,

    CC1312R1_SMARTSENSOR_TRNGCOUNT
} CC1312R1_SMARTSENSOR_TRNGName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_GPIOName
 *  @brief  Enum of GPIO names
 */
typedef enum CC1312R1_SMARTSENSOR_GPIOName {
    CC1312R1_SMARTSENSOR_GPIO_STM_NRST = 0,
    CC1312R1_SMARTSENSOR_GPIO_STM_BOOT,
    CC1312R1_SMARTSENSOR_GPIO_SPI_FLASH_CS,
    CC1312R1_SMARTSENSOR_GPIO_SPI_FLASH_WP,
    CC1312R1_SMARTSENSOR_GPIO_SPI_FLASH_HOLD,
    CC1312R1_SMARTSENSOR_GPIOCOUNT
} CC1312R1_SMARTSENSOR_GPIOName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_GPTimerName
 *  @brief  Enum of GPTimer parts
 */
typedef enum CC1312R1_SMARTSENSOR_GPTimerName {
    CC1312R1_SMARTSENSOR_GPTIMER0A = 0,
    CC1312R1_SMARTSENSOR_GPTIMER0B,
    CC1312R1_SMARTSENSOR_GPTIMER1A,
    CC1312R1_SMARTSENSOR_GPTIMER1B,
    CC1312R1_SMARTSENSOR_GPTIMER2A,
    CC1312R1_SMARTSENSOR_GPTIMER2B,
    CC1312R1_SMARTSENSOR_GPTIMER3A,
    CC1312R1_SMARTSENSOR_GPTIMER3B,

    CC1312R1_SMARTSENSOR_GPTIMERPARTSCOUNT
} CC1312R1_SMARTSENSOR_GPTimerName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_GPTimers
 *  @brief  Enum of GPTimers
 */
typedef enum CC1312R1_SMARTSENSOR_GPTimers {
    CC1312R1_SMARTSENSOR_GPTIMER0 = 0,
    CC1312R1_SMARTSENSOR_GPTIMER1,
    CC1312R1_SMARTSENSOR_GPTIMER2,
    CC1312R1_SMARTSENSOR_GPTIMER3,

    CC1312R1_SMARTSENSOR_GPTIMERCOUNT
} CC1312R1_SMARTSENSOR_GPTimers;

/*!
 *  @def    CC1312R1_SMARTSENSOR_I2CName
 *  @brief  Enum of I2C names
 */
typedef enum CC1312R1_SMARTSENSOR_I2CName {
#if TI_I2C_CONF_I2C0_ENABLE
    CC1312R1_SMARTSENSOR_I2C0 = 0,
#endif

    CC1312R1_SMARTSENSOR_I2CCOUNT
} CC1312R1_SMARTSENSOR_I2CName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_I2SName
 *  @brief  Enum of I2S names
 */
typedef enum CC1312R1_SMARTSENSOR_I2SName {
    CC1312R1_SMARTSENSOR_I2S0 = 0,

    CC1312R1_SMARTSENSOR_I2SCOUNT
} CC1312R1_SMARTSENSOR_I2SName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_NVSName
 *  @brief  Enum of NVS names
 */
typedef enum CC1312R1_SMARTSENSOR_NVSName {
#if TI_NVS_CONF_NVS_INTERNAL_ENABLE
    CC1312R1_SMARTSENSOR_NVSCC26XX0 = 0,
#endif
#if TI_NVS_CONF_NVS_EXTERNAL_ENABLE
    CC1312R1_SMARTSENSOR_NVSSPI25X0,
#endif

    CC1312R1_SMARTSENSOR_NVSCOUNT
} CC1312R1_SMARTSENSOR_NVSName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_PWMName
 *  @brief  Enum of PWM outputs
 */
typedef enum CC1312R1_SMARTSENSOR_PWMName {
    CC1312R1_SMARTSENSOR_PWM0 = 0,
    CC1312R1_SMARTSENSOR_PWM1,
    CC1312R1_SMARTSENSOR_PWM2,
    CC1312R1_SMARTSENSOR_PWM3,
    CC1312R1_SMARTSENSOR_PWM4,
    CC1312R1_SMARTSENSOR_PWM5,
    CC1312R1_SMARTSENSOR_PWM6,
    CC1312R1_SMARTSENSOR_PWM7,

    CC1312R1_SMARTSENSOR_PWMCOUNT
} CC1312R1_SMARTSENSOR_PWMName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_SDName
 *  @brief  Enum of SD names
 */
typedef enum CC1312R1_SMARTSENSOR_SDName {
    CC1312R1_SMARTSENSOR_SDSPI0 = 0,

    CC1312R1_SMARTSENSOR_SDCOUNT
} CC1312R1_SMARTSENSOR_SDName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_SPIName
 *  @brief  Enum of SPI names
 */
typedef enum CC1312R1_SMARTSENSOR_SPIName {
#if TI_SPI_CONF_SPI0_ENABLE
    CC1312R1_SMARTSENSOR_SPI0 = 0,
#endif
#if TI_SPI_CONF_SPI1_ENABLE
    CC1312R1_SMARTSENSOR_SPI1,
#endif

    CC1312R1_SMARTSENSOR_SPICOUNT
} CC1312R1_SMARTSENSOR_SPIName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_UARTName
 *  @brief  Enum of UARTs
 */
typedef enum CC1312R1_SMARTSENSOR_UARTName {
#if TI_UART_CONF_UART0_ENABLE
    CC1312R1_SMARTSENSOR_UART0 = 0,
#endif
#if TI_UART_CONF_UART1_ENABLE
    CC1312R1_SMARTSENSOR_UART1,
#endif

    CC1312R1_SMARTSENSOR_UARTCOUNT
} CC1312R1_SMARTSENSOR_UARTName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_UDMAName
 *  @brief  Enum of DMA buffers
 */
typedef enum CC1312R1_SMARTSENSOR_UDMAName {
    CC1312R1_SMARTSENSOR_UDMA0 = 0,

    CC1312R1_SMARTSENSOR_UDMACOUNT
} CC1312R1_SMARTSENSOR_UDMAName;

/*!
 *  @def    CC1312R1_SMARTSENSOR_WatchdogName
 *  @brief  Enum of Watchdogs
 */
typedef enum CC1312R1_SMARTSENSOR_WatchdogName {
    CC1312R1_SMARTSENSOR_WATCHDOG0 = 0,

    CC1312R1_SMARTSENSOR_WATCHDOGCOUNT
} CC1312R1_SMARTSENSOR_WatchdogName;


#ifdef __cplusplus
}
#endif

#endif /* __CC1312R1_SMARTSENSOR_BOARD_H__ */
