################################################################################
# SimpleLink SmartCom makefile

BOARD_TYPE = BOARD_SMARTCOM

# leds-arch.c etc.
BOARD_SOURCEFILES += button-sensor-arch.c leds-arch.c

TARGET_FAMILY_DIRS += smartcom
