include $(CONTIKI)/Makefile.identify-target

# Include BR variant depending on platform and also generic BR code for all
# embedded platforms
MODULES += os/services/rpl-border-router/$(TARGET)

ifeq ($(BOARD),smartcom/cc1352R1)
  MODULES += os/services/rpl-border-router/smartcom
else
  ifneq ($(TARGET),native)
    MODULES += os/services/rpl-border-router/embedded
  endif
endif